created class for ai image generation and a demo
imaginate-ai/api pull request #5
Opened 2024-06-11 04:46 UTC by proby-8

Built a class for ai image generation, runs 'out of the box' but may/will require further testing and experimentation with hyper parameters to achieve good, consistent results.

Currently supports image to image and text to image.

Also created an asynchronous queue such that the script will generate one image at a time (to save the GPU) but will run another thread that can check for input to allow continuous image generation. The example used is a simple one, but this could allow us to leave the script running and send images/prompts asynchronously, e.g even link it to a database or another script.

A lot of it was trial and error, so if there is anything to change off the top of your heads let me know while most of it is still fresh in my mind.

2024-06-13 01:19 UTC, zachale requested changes
LGTM! 🚀 
Great First PR! I have a few minor comments, let me know if I am wrong.

2024-06-13 01:19 UTC, zachale commented on ImageHandler.py
> +            if task is None:
nit: could it be best practice for readability to put the positive case in the conditional?
```suggestion
            if task:
                print(f"\nDequeued: {task['kwargs']['prompt']}")
                self.process(task)
                self.queue.task_done()
            else:
                 break
```

2024-06-13 01:19 UTC, zachale commented on ImageHandler.py
> +        if num_inference_steps is not None:
I think you could [simplify ](https://note.nkmk.me/en/python-none-usage) this if statement
```suggestion
        if num_inference_steps:
```

2024-06-13 01:19 UTC, zachale commented on ImageHandler.py
> +        if guidance_scale is not None:
There are a handful of places just like this. Take a look at them and see if it's possible to optimize them!

2024-06-13 02:21 UTC, faisal-fawad commented
Pretty good! Cool data structure and clean usage of kwargs :) Apart from Zach's suggestions I don't think there is anything really... I did notice that there are two possible types: "image" and "prompt"; instead of using a string here it may be better practice to use an enumeration (?) though it isn't too big of a deal

2024-06-16 02:49 UTC, faisal-fawad approved these changes

2024-06-17 21:28 UTC, zachale approved these changes

2024-06-17 21:45 UTC, merged